# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669b24d3e7c263df865a9fe09bed6787f4cd9735d658c175d97699628f3a365058a9480dd76839232d79fac0b9833355f2abe37380508eb7c6995cad4764c32e

test:
  secret_key_base: 8db5877772d5d1104ba2d42c2fd34c67db21cb719e226f234fb1076191f586214c49b1fca3987b708ad574045bef6ba2c62ec78128614c8273a03cf44a9ab485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
